chore: adjust verify action parameters

diff --git a/actions/shared/verify_installation/action.yml b/actions/shared/verify_installation/action.yml
--- a/actions/shared/verify_installation/action.yml
+++ b/actions/shared/verify_installation/action.yml
@@ -99,57 +99,65 @@ runs:
             case $cr_exit_code in
               0)
                 echo "✅ CR check successful"
-                cr_success=true ;;
+                cr_success=true
+                break
+                ;;
               1)
-                echo "⏳ CR check in progress" ;;
+                echo "⏳ CR check in progress"
+                echo -e "Retrying in ${{inputs.service_ready_retry_interval}} seconds...\n"
+                sleep ${{inputs.service_ready_retry_interval}}
+                ;;
               2)
                 echo "::error:: ❌ CR check failed"
                 echo "ERROR_FLAG=true" >> $GITHUB_ENV
-                break ;;
+                break
+                ;;
             esac
           fi
-
-          if [ "$resources_success" = "false" ]; then
-            set +e
-            ./qubership-test-pipelines/scripts/check_resources.sh "${{inputs.namespace}}"
-            resources_exit_code=$?
-            set -e
-
-            if [ $resources_exit_code -eq 0 ]; then
-              echo "✅ Resources checks successful"
-              resources_success=true
-            elif [ $resources_exit_code -eq 1 ]; then
-              echo "⏳ Some resources are not ready"
-              echo "PODS:"
-              kubectl get pods -n "${{inputs.namespace}}"
-            fi
+          done
+          if [[ "${{ inputs.monitoring_pipeline }}" == "true" ]]; then
+                # ▶️ Check monitoring CRs statuses
+                echo "Checking VictoriaMetrics CRs in namespace: ${{inputs.namespace}}"
+                chmod +x ./qubership-test-pipelines/scripts/check-vm-cr-statuses.sh
+                echo $(pwd)
+                echo "${{inputs.repository_name}}/.github/expected-vm-cr-statuses.json"
+                cat "${{inputs.repository_name}}/.github/expected-vm-cr-statuses.json"
+                ./qubership-test-pipelines/scripts/check-vm-cr-statuses.sh ${{inputs.namespace}} ${{inputs.service_ready_max_retries}} ${{inputs.service_ready_retry_interval}} ${{inputs.repository_name}}/.github/expected-vm-cr-statuses.json
           fi
+          for i in {1..${{inputs.service_ready_max_retries}}}; do
+            echo "Attempt $i/${{inputs.service_ready_max_retries}}"
+            if [ "$resources_success" = "false" ]; then
+              set +e
+              ./qubership-test-pipelines/scripts/check_resources.sh "${{inputs.namespace}}"
+              resources_exit_code=$?
+              set -e
+  
+              if [ $resources_exit_code -eq 0 ]; then
+                echo "✅ Resources checks successful"
+                resources_success=true
+                break
+              elif [ $resources_exit_code -eq 1 ]; then
+                echo "⏳ Some resources are not ready"
+                echo "PODS:"
+                kubectl get pods -n "${{inputs.namespace}}"
+              fi
+            fi
+          done
 
           if [ "$cr_success" = "true" ] && [ "$resources_success" = "true" ]; then
             echo "✅ All checks completed successfully!"
-            break
+            exit 0
           fi
-
-          if [ $i -ne ${{inputs.service_ready_max_retries}} ]; then
-            echo -e "Retrying in ${{inputs.service_ready_retry_interval}} seconds...\n"
-            sleep ${{inputs.service_ready_retry_interval}}
-          else
-            if [ "$cr_success" = "false" ]; then
-              echo "::error:: ❌ CR check not successful after ${{inputs.service_ready_max_retries}} retries"
-              echo "ERROR_FLAG=true" >> $GITHUB_ENV
-            fi
-            if [ "$resources_success" = "false" ]; then
-              echo "::error:: ❌ Resources not ready after ${{inputs.service_ready_max_retries}} retries"
-              echo "ERROR_FLAG=true" >> $GITHUB_ENV
-            fi
+          if [ "$cr_success" = "false" ]; then
+            echo "::error:: ❌ CR check not successful after ${{inputs.service_ready_max_retries}} retries"
+            echo "ERROR_FLAG=true" >> $GITHUB_ENV
+            exit 1
           fi
-        done
-        if [[ "${{ inputs.monitoring_pipeline }}" == "true" ]]; then
-              # ▶️ Check monitoring CRs statuses
-              echo "Checking VictoriaMetrics CRs in namespace: ${{inputs.namespace}}"
-              chmod +x ./qubership-test-pipelines/scripts/check-vm-cr-statuses.sh
-              ./qubership-test-pipelines/scripts/check-vm-cr-statuses.sh ${{inputs.namespace}} ${{inputs.service_ready_max_retries}} ${{inputs.service_ready_retry_interval}} ${{inputs.repository_name}}/.github/expected-vm-cr-statuses.json
-        fi
+          if [ "$resources_success" = "false" ]; then
+            echo "::error:: ❌ Resources not ready after ${{inputs.service_ready_max_retries}} retries"
+            echo "ERROR_FLAG=true" >> $GITHUB_ENV
+            exit 1
+          fi
   
     - name: Get logs from test pod
       if: ${{ inputs.check_tests == 'true' }}
@@ -276,7 +284,7 @@ runs:
               echo "$pod $container" >> "$file_name"
               kubectl logs "$pod" -n "${{inputs.namespace}}" -c "$container" >> "$file_name"
               echo "================================================================================" >> "$file_name"
-              kubectl logs "$pod" -n "${{inputs.namespace}}" -c "$container" --previous >> "${file_name}_previous.txt" || echo "No previous logs for $pod $container" >> "{file_name}_previous.txt"
+              kubectl logs "$pod" -n "${{inputs.namespace}}" -c "$container" --previous >> "previous_${file_name}.txt" 2>/dev/null || echo "No previous logs for $pod $container" >> "previous_${file_name}.txt"
             done
         done
 
